export const USER_LOGGED_REQUEST = 'USER_LOGGED_REQUEST';
export const USER_LOGGED_SUCCESS = 'USER_LOGGED_SUCCESS';
export const USER_LOGGED_ERROR = 'USER_LOGGED_ERROR';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_ADD_TODO_ITEM = 'USER_ADD_TODO_ITEM';
export const FETCH_TODO_ITEM = 'FETCH_TODO_ITEM';
export const CREATE_USER = 'CREATE_USER';
